name: red_social
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  shared_preferences: ^2.5.2
  firebase_core: ^2.32.0  # Última versión estable
  cloud_firestore: ^4.17.0  # Última versión estable de Firestore
  firebase_auth: ^4.17.0  # Última versión estable de autenticación
  mongo_dart: ^0.10.4
  firebase_storage: ^11.0.10
  path_provider: ^2.0.11




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
