// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform, 
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: "AIzaSyCJJQiSt6fo7V0r9FDpqzlJORWQwkWq0K4",
      authDomain: "bbdd-red-social.firebaseapp.com",
      projectId: "bbdd-red-social",
      storageBucket: "bbdd-red-social.firebasestorage.app",
      messagingSenderId: "1050104026404",
      appId: "1:1050104026404:web:5244f68122b8e8d3b54fb1"
    );
  }
}